# Chapter 2: Individual security returns

Based on [Analyzing Financial Data and Implementing Financial Models Using R](https://www.amazon.com/Analyzing-Financial-Implementing-Springer-Economics/dp/3030641546) by Clifford S. Ang (Springer), but we're using Python instead of R.

This notebook is based on the first edition. There's a newer second edition of the book but I don't have it.

In [1]:
import pandas as pd
import yfinance as yf

# Cache API calls
import requests_cache

In [2]:
# FIXME Temporarily pinning pandas to 1.3.5 since 1.4.0 breaks Ticker.history() in yfinance 0.1.69.
# See https://github.com/ranaroussi/yfinance/issues/937. After yfinance updates this, we can remove
# the pandas version pin.
pd.__version__

'1.3.5'

In [3]:
yf.__version__

'0.1.69'

In [4]:
session = requests_cache.CachedSession("yfinance.cache")
session.headers["User-Agent"] = "prices-notebook/1.0"
o = yf.Ticker("O", session=session)

## 2.1 Price returns

The price return is the percentage change in the closing price of a security. For example, if a security goes from \\$100 to \\$120 over some time period, then the price return is 20%.

$$ PRet_t = \frac{P_t - P_{t-1}}{P_{t-1}} = \frac{P_t}{P_{t-1}} - 1$$

Price returns include capital gains, and exclude intermediate cash flows such as stock dividends or bond coupons.

Note also that the prices below are adjusted for splits and dividend and/or capital gain distributions.

In [5]:
o_df = o.history(start="2021-12-01", end="2021-12-31", auto_adjust=False, back_adjust=False)
o_df

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2021-12-01,68.449997,69.089996,65.900002,65.919998,65.693573,6009300.0,0.000,0
2021-12-02,66.550003,68.059998,66.419998,67.519997,67.288078,5086200.0,0.000,0
2021-12-03,67.580002,67.879997,66.830002,67.250000,67.019005,4045500.0,0.000,0
2021-12-06,67.769997,69.580002,67.709999,68.080002,67.846161,5604700.0,0.000,0
2021-12-07,68.400002,68.879997,68.040001,68.389999,68.155090,6229000.0,0.000,0
2021-12-08,68.349998,69.089996,68.239998,68.849998,68.613510,4298400.0,0.000,0
2021-12-09,68.519997,68.519997,67.339996,67.360001,67.128632,3697900.0,0.000,0
2021-12-10,67.809998,67.809998,66.889999,66.940002,66.710075,3873900.0,0.000,0
2021-12-13,66.989998,68.470001,66.849998,68.160004,67.925888,4984500.0,0.000,0
2021-12-14,68.099998,68.639999,67.250000,67.290001,67.058868,4766400.0,0.000,0
2021-12-15,67.000000,67.379997,65.650002,67.220001,66.989113,6006200.0,0.000,0
2021-12-16,67.440002,68.000000,67.139999,67.669998,67.437561,5136800.0,0.000,0
2021-12-17,67.650002,68.669998,67.550003,67.779999,67.547188,12326900.0,0.000,0
2021-12-20,67.139999,67.379997,66.360001,67.260002,67.028976,3914000.0,0.000,0
2021-12-21,67.589996,68.860001,67.559998,68.730003,68.493927,4084300.0,0.000,0
2021-12-22,68.900002,69.239998,68.459999,69.139999,68.902512,2989200.0,0.000,0
2021-12-23,69.250000,69.419998,68.860001,69.220001,68.982239,2863700.0,0.000,0
2021-12-27,69.250000,70.949997,69.239998,70.940002,70.696335,3346100.0,0.000,0
2021-12-28,70.879997,71.510002,70.739998,71.400002,71.154755,2663800.0,0.000,0
2021-12-29,71.500000,72.029999,71.309998,71.900002,71.653038,1920100.0,0.000,0
2021-12-30,72.000000,72.209999,71.510002,71.910004,71.663002,2071500.0,0.000,0
2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,0.247,0

In [6]:
# Discard OHLV and splits as we don't need those.
o_df = o_df.loc[:, ["Close", "Dividends"]]
o_df

                Close  Dividends
Date
2021-12-01  65.919998      0.000
2021-12-02  67.519997      0.000
2021-12-03  67.250000      0.000
2021-12-06  68.080002      0.000
2021-12-07  68.389999      0.000
2021-12-08  68.849998      0.000
2021-12-09  67.360001      0.000
2021-12-10  66.940002      0.000
2021-12-13  68.160004      0.000
2021-12-14  67.290001      0.000
2021-12-15  67.220001      0.000
2021-12-16  67.669998      0.000
2021-12-17  67.779999      0.000
2021-12-20  67.260002      0.000
2021-12-21  68.730003      0.000
2021-12-22  69.139999      0.000
2021-12-23  69.220001      0.000
2021-12-27  70.940002      0.000
2021-12-28  71.400002      0.000
2021-12-29  71.900002      0.000
2021-12-30  71.910004      0.000
2021-12-31        NaN      0.247

In [7]:
# Calculate price return.
# Pandas has a ready-made pct_change() function for this.
# NOTE: This procedure does _not_ account for stock splits.
o_df["PriceReturn"] = o_df["Close"].pct_change()
o_df

                Close  Dividends  PriceReturn
Date
2021-12-01  65.919998      0.000          NaN
2021-12-02  67.519997      0.000     0.024272
2021-12-03  67.250000      0.000    -0.003999
2021-12-06  68.080002      0.000     0.012342
2021-12-07  68.389999      0.000     0.004553
2021-12-08  68.849998      0.000     0.006726
2021-12-09  67.360001      0.000    -0.021641
2021-12-10  66.940002      0.000    -0.006235
2021-12-13  68.160004      0.000     0.018225
2021-12-14  67.290001      0.000    -0.012764
2021-12-15  67.220001      0.000    -0.001040
2021-12-16  67.669998      0.000     0.006694
2021-12-17  67.779999      0.000     0.001626
2021-12-20  67.260002      0.000    -0.007672
2021-12-21  68.730003      0.000     0.021856
2021-12-22  69.139999      0.000     0.005965
2021-12-23  69.220001      0.000     0.001157
2021-12-27  70.940002      0.000     0.024848
2021-12-28  71.400002      0.000     0.006484
2021-12-29  71.900002      0.000     0.007003
2021-12-30  71.910004      0.000     0.000139
2021-12-31        NaN      0.247     0.000000

## 2.2 Total returns

Also known as _holding period returns_. This includes both the capital gain and intermediate cash flows.

$$
R_t 
  = \frac{P_t + CF_t - P_{t-1}}{P_{t-1}} 
  = \underbrace{ \left[ \frac{P_t}{P_{t-1}} - 1 \right]}_\text{Capital gain}
    + \underbrace{ \frac{CF_t}{P_{t-1}} }_\text{CF yield}
$$

(Note that the equation above corrects an error in the book.)

In [8]:
o_df["TotalReturn"] = o_df["PriceReturn"] + o_df["Dividends"] / o_df["Close"].shift(1)

In [9]:
o_df

                Close  Dividends  PriceReturn  TotalReturn
Date
2021-12-01  65.919998      0.000          NaN          NaN
2021-12-02  67.519997      0.000     0.024272     0.024272
2021-12-03  67.250000      0.000    -0.003999    -0.003999
2021-12-06  68.080002      0.000     0.012342     0.012342
2021-12-07  68.389999      0.000     0.004553     0.004553
2021-12-08  68.849998      0.000     0.006726     0.006726
2021-12-09  67.360001      0.000    -0.021641    -0.021641
2021-12-10  66.940002      0.000    -0.006235    -0.006235
2021-12-13  68.160004      0.000     0.018225     0.018225
2021-12-14  67.290001      0.000    -0.012764    -0.012764
2021-12-15  67.220001      0.000    -0.001040    -0.001040
2021-12-16  67.669998      0.000     0.006694     0.006694
2021-12-17  67.779999      0.000     0.001626     0.001626
2021-12-20  67.260002      0.000    -0.007672    -0.007672
2021-12-21  68.730003      0.000     0.021856     0.021856
2021-12-22  69.139999      0.000     0.005965     0.005965
2021-12-23  69.220001      0.000     0.001157     0.001157
2021-12-27  70.940002      0.000     0.024848     0.024848
2021-12-28  71.400002      0.000     0.006484     0.006484
2021-12-29  71.900002      0.000     0.007003     0.007003
2021-12-30  71.910004      0.000     0.000139     0.000139
2021-12-31        NaN      0.247     0.000000     0.003435

## 2.3 Logarithmic total returns

## 2.4 Cumulating multi-day returns

## 2.5 Weekly returns

## 2.6 Monthly returns

## 2.7 Comparing performance of multiple securities: total returns